# Site settings
title: J.H blog
# baseurl: "/ap"
url: "https://github.com/jjunh33"
google_analytics: G-VXY5KFRLP5

# Author
author:
  name: JunHyeok Lee
  desc: Hello nice to meet you
  email: jjunh33@gmail.com
  selfie: assets/img/profile.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  # facebook: Test
  flickr:
  github: jjunh33
  google_plus:
  instagram: junhyuk0304
  keybase:
  # linkedin: https://www.linkedin.com/in/kssim/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  # twitter: Test
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"

# Custom vars
comment:
  provider: "disqus"
  disqus:
    shortname: "jjunh33"
